title: Rogier van den Berg
author: Rogier van den Berg
email: mail@rogier.nu
description: 'Co-Founder van Embrosa (@EmbrosaNL) #StartUp Online specialist, software-engineer,
marketeer. Getrouwd en papa. Verbindt mensen, gek op techniek. '
show_excerpts: true # set to true to show excerpts on the homepage
baseurl: ''

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: "/:title/"
texture:
  title: Rogier van den Berg
  tagline: Co-Founder Embrosa. Developer.
  date_format: "%b %-d"
  style: blue
  showNav: true
  showPicker: false

  # generate social links in footer
  social_links:
    twitter: rogiervdberg
    github:  rogiervandenberg
    linkedIn: in/rogiervandenberg
    rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed