---
title: Rogier van den Berg
timezone: CET
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: img
  values:
    image: true
email: mail@rogier.nu
description: 'Co-Founder van Embrosa (@EmbrosaNL) #StartUp Online specialist, software-engineer,
  marketeer. Getrouwd en papa. Verbindt mensen, gek op techniek. '
baseurl: ''
url: http://www.rogiervandenberg.nl
paginate: 5
twitter_username: rogiervdberg
github_username: rogiervandenberg
markdown: kramdown
theme: minima
permalink: "/:title/"
plugins:
- jekyll-paginate
- jekyll-feed
